### 获取用户列表 username 非必填
GET http://localhost:8888/user/list

### 获取用户列表 username 模糊查询
GET http://localhost:8888/user/list?username=张

### 分页获取用户列表 pagehelper
GET http://localhost:8888/user/list/pagehelper?pageNum=1&pageSize=3&username=张
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmFtZSI6InRlc3QiLCJpYXQiOjE2ODc0ODcwMjAsImV4cCI6MTY4NzQ4NzA4MH0.U37eAK-Vw060AVz0hD2cvpArobJ-0T-l_SUFwWeB9uQ

### 分页获取用户列表 mybatis mapper page
GET http://localhost:8888/user/list/page/mapper?pageNum=1&pageSize=3&username=张

### 分页获取用户列表 mybatis service page
GET http://localhost:8888/user/list/page/service?pageNum=1&pageSize=3&username=张
