### 验证RequestParam参数：验证失败
GET http://localhost:8888/validate/requestparam

### 验证RequestParam参数：验证成功
GET http://localhost:8888/validate/requestparam?param1=1


### 验证RequestBody参数 ： 验证失败
POST http://localhost:8888/validate/requestbody
Content-Type: application/json

{
  "param1": "2"
}

### 验证RequestBody参数 ： 验证成功
POST http://localhost:8888/validate/requestbody
Content-Type: application/json

{
  "param1": "1",
  "param2": "2"
}


